### ISSUE TITLE
Multithreaded emitting seems to be broken

### ISSUE THREAD

**Issue by msukmanowsky** [Parsely/streamparse#101]
See discussion here https://groups.google.com/forum/#!topic/streamparse/_Wz9zO-d6Yw. Although we have some basic locking around no two threads writing to stdout/reading from stdin, seems as though we need to have a more careful look at other state for bolts/spouts that could be modified by multithreaded bolts and ensure everything works properly.

**Comment by kbourgoin** [comment]
I'm pretty sure the root cause is in here:  https://github.com/Parsely/streamparse/blob/master/streamparse/bolt.py#L134-L147

There should probably be a lock around the entire send_message/read_task_ids part to ensure it happens in the proper order. Otherwise, it's possible to get task ids from the wrong emit.

Somewhat unrelated, but why `need_task_ids=None` and not `need_task_ids=True`?  We just set it to `True` if it's None anyway.

**Comment by msukmanowsky** [comment]
Agree with giving the lock another look, the `None` versus `True` thing was just me being tired when adding kwargs :).
