### ISSUE TITLE
Allow non-uberjar deploys for speed & simplicity

### ISSUE THREAD

**Issue by amontalenti** [Parsely/streamparse#106]
We currently have `lein uberjar` running in these lines:

https://github.com/Parsely/streamparse/blob/master/streamparse/ext/invoke.py#L135-L146

That makes the JAR file contain Storm + all its JAR dependencies, which explodes the topology JAR size and makes deploys slow. A Python codebase that is only 20-30KB ends up being a 15MB JAR to submit.

The non-uberjar is built (it's the one without `-standalone`) but we are uploading the uberjar.

**Comment by hellp** [comment]
How is the status on this? Can this be solved?

**Comment by kbourgoin** [comment]
We haven't had any time to work on this yet, but it's definitely solvable.

**Comment by emidln** [comment]
Storm expects all of the dependencies to be available in your submitted jar. While you could submit something else, your devops environment would be responsible for setting the appropriate dependencies in your classpath. That would also entail global specification of dependency versions, which seems bad.

**Comment by kbourgoin** [comment]
In our experience, this only matters when you're including other JVM dependencies.  If your topology is pure python, then you can get away with only submitting the python code since it already has the Storm-specific dependencies.  We used to use Petrel, which constructed the jar as a zipfile, without any JVM dependencies included, and the resulting jars were much, much smaller.

That's really the only case we were thinking of.  To do as you're suggesting sounds like a nightmare.

**Comment by emidln** [comment]
Ah, fair enough. I'm making use of a jvm spout and several jvm-based bolts. A pure-python use case would indeed only have to do minor gymnastics to make sure the JAR was valid.

**Comment by amontalenti** [comment]
Reviewing and fixing this logic might be a good issue for a first pull request, @cabiad.
