### ISSUE TITLE
Streamparse calling next_tuple continuously

### ISSUE THREAD

**Issue by coffenbacher** [Parsely/streamparse#111]
Everything is working in my quite basic topology except the simple Kafka spout that I wrote - it seems to just continuously call "next_tuple". My bolts are fairly slow, so the system seems to very quickly explode in memory as the spout adds too many messages. If the problem/solution is non-obvious from the information provided here, I can try to modify one of the example projects to provide a working repro.

Launching the topology, I tried to set topology.max.spout.pending to 1 to prevent it from adding too many messages to the topology.

    lein run -m streamparse.commands.run/-main topologies/.clj -t 100 --option 'topology.max.spout.pending=1' --option 'topology.workers=1' --option 'topology.acker.executors=1' 

However, the result is this, despite the bolts being much slower than the spout:

    24790 [Thread-16-metadata-spout] INFO  backtype.storm.spout.ShellSpout - Shell msg: ----NEXT TUPLE----
    24942 [Thread-16-metadata-spout] INFO  backtype.storm.spout.ShellSpout - Shell msg: ----NEXT TUPLE----
    24944 [Thread-16-metadata-spout] INFO  backtype.storm.spout.ShellSpout - Shell msg: ----NEXT TUPLE----
    24946 [Thread-16-metadata-spout] INFO  backtype.storm.spout.ShellSpout - Shell msg: ----NEXT TUPLE----
    25143 [Thread-16-metadata-spout] INFO  backtype.storm.spout.ShellSpout - Shell msg: ----NEXT TUPLE----
    25144 [Thread-16-metadata-spout] INFO  backtype.storm.spout.ShellSpout - Shell msg: ----NEXT TUPLE----
    25350 [Thread-16-metadata-spout] INFO  backtype.storm.spout.ShellSpout - Shell msg: ----NEXT TUPLE----
    ......

My simple Kafka spout:

    class MetadataSpout(Spout):
    
        def initialize(self, stormconf, context):
            self.log('----CONFIG: %s----' % stormconf)
            k = KafkaClient(os.getenv('KAFKA'))
            self.consumer = SimpleConsumer(k, 'vacuum', 'metadata')
    
        def next_tuple(self):
            self.log('----NEXT TUPLE----')
            messages = self.consumer.get_messages(count=os.getenv('BATCH_COUNT', 20))
            self.emit([json.dumps([m.message.value for m in messages])])

My bolts have just the default ack configuration, but take a significant amount of time to complete the process() method. I cannot figure out how they could be the problem, but I can post if they're relevant.

**Comment by kbourgoin** [comment]
Hi there,

This isn't actually an issue, but a consequence of how Storm is designed.  `next_tuple` is being continuously called because the Storm worker is constantly asking for more tuples.

There are a few ways you can solve the issue.  First, you can increase bolt parallelism so that your bolts are able to handle the volume produced by the spout. In practice, this is very difficult because of how insanely fast Kafka is.  If you have a substantial backlog in Kafka, it's almost always going to swamp your workers.

Ultimately, the setting you want is `topology.max.spout.pending`.  This will control the number of pending tuples that each spout has within the topology.  The default in Storm is to have this unlimited, which is why it keeps asking for more tuples.  If you have it turned on, then it'll stop asking for tuples when the topology is "full".  To use this setting, just add this to your sparse call: `-o topology.max.spout.pending=SOME_NUMBER`

**Comment by dan-blanchard** [comment]
`topology.max.spout.pending` only has an effect if your spout is reliable (see [official Storm docs](https://storm.apache.org/apidocs/backtype/storm/Config.html#TOPOLOGY_MAX_SPOUT_PENDING)).  You'll need to specify the optional `tup_id` parameter to `emit` to give each tuple a unique ID.  Once you do that, all should be well.

**Comment by kbourgoin** [comment]
Sorry, first thing in the morning. I read the bit about setting pending to 1 as having set parallelism to 1.  Dan's right on this one.

**Comment by coffenbacher** [comment]
Works great now! Thanks all. Really enjoying streamparse.
