### ISSUE TITLE
Handle tick tuples in Bolt base class

### ISSUE THREAD

**Issue by xaratt** [Parsely/streamparse#116]
Streamparse's support of the Storm's tick tuple isn't obvious. Adding something like this
```python
    def is_tick_tuple(self, tup):
        return tup.component == '__system' and tup.stream == '__tick'
```
to class streamparse.bolt.Bolt could help newbies (like me).

Also modifying wordcount.clj will be helpful too:
```closure
"count-bolt" (python-bolt-spec
...
:p 2
:conf {"topology.tick.tuple.freq.secs", 60}
)
```

**Comment by amontalenti** [comment]
I don't think you can add `:conf` to the bolt in order to specify tick tuples. I believe they are a topology-wide setting (thus the `topology.` prefix). However, you can flip tick tuples on:

    sparse run -o "topology.tick.tuple.freq.secs=1" -t 10 -d

In this case, you end up seeing the following in the debug output:

    11960 [Thread-22-count-bolt] INFO  backtype.storm.daemon.executor - Execute done TUPLE source: __system:-1, stream: __tick, id: {}, [2] TASK: 4 DELTA:

We discussed how to handle this. We'll have a method called `process_tick()` that only gets called when the tuple is actually tick tuple, and ticks won't get passed to `process()`, because otherwise they mess with unpacking logic and such. @cabiad says he's going to try this one for size at PyCon.

**Comment by dan-blanchard** [comment]
Yeah, the Pyleus guys actually beat us to the bunch on this one.  Also, @amontalenti, please make sure anyone working uses the latest version of master as their base, because I just merged in a major reorg.
