### ISSUE TITLE
Mac OS X Java and lein instructions with homebrew

### ISSUE THREAD

**Issue by amontalenti** [Parsely/streamparse#117]
At PyCon, @omus reported that it was easier to get streamparse running with its only two Java dependencies (JDK itself and lein) via homebrew "cask".

**Comment by dan-blanchard** [comment]
They're also both available as conda packages via my conda_channel, by adding `-c dan_blanchard` to your `conda install` command.

**Comment by omus** [comment]
Instructions are `brew install leiningen` and `brew cask install java`. The later statement requires that you have [cask](https://github.com/caskroom/homebrew-cask) which can be installed with `brew install caskroom/cask/brew-cask`.

**Comment by rduplain** [comment]
There may be a reliable option without `homebrew` as well. In my experience, recent versions of Mac OS X will provide an installer for `java` when it is invoked.

Open a Terminal and type: `java -version`. This will invoke a GUI to install the JDK. Follow the instructions of the GUI and you should be set.

Since the `lein` script is self-installing (as mentioned in #139), you can just grab `lein`, put it in your `$PATH` and run it.

**Comment by dan-blanchard** [comment]
> Since the lein script is self-installing (as mentioned in #139), you can just grab lein, put it in your $PATH and run it.

That seems like the simplest set of instructions.

**Comment by dan-blanchard** [comment]
We mention in the instructions now that you can use apt-get, lein, homebrew, etc. to install these, so I'm closing this.
