### ISSUE TITLE
Proposal: Have dynamic `process_stream` methods in Bolts

### ISSUE THREAD

**Issue by amontalenti** [Parsely/streamparse#120]
So, we were discussing one way to improve the Bolt base classs. In #84 we are working on a topology proposal that would involve adding a class variable called `streams` that lists either the fields of the default stream, or the field specifications for all streams that a Bolt supports. The other side of this is how Bolts can handle incoming streams of data.

One thought we had is that the typical first line of a `process` method could be improved, e.g.

```python
def process(self, tup):
    var1, var2, var3 = tup.values
    # do something
```

To look more like this:

```python
def process_default(self, var1, var2, var3):
    # do something
```

The idea would be that `process_default` handles the `default` stream, and it would `*-apply` the `tup.values`, e.g. it would look something like this in the IPC layer:

```python
    stream = tup.stream
    values = tup.values
    method = getattr(self, "process_%s" % stream)
    try:
        if method is not None:
            method(*values)
    except SomeException: pass
```

This would have some caveats -- e.g., what would happen with weird stream names. Maybe we'd only support this on the `default` stream for now. Also, should we support something special like `process_all` for handling all tuples regardless of stream? Anyway, this is just an idea/proposal for now.

(Came out of discussion with @cabiad and @omus at PyCon sprints.)

**Comment by dan-blanchard** [comment]
I'm kind of torn about this.  At first I was going to say that I think this is a great idea, but then I realized:

1.  You need `tup` to `ack` or `fail` the tuple from within your `process` method.  If you're using `auto_ack` and `auto_fail`, that's not a problem, but with more complex topologies, you usually want more control over when the acking and failing occurs.
2.  Sometimes your bolt might want to do some processing based on the other attributes of the `Tuple` class, namely `id`, `task`, or `component`.  I've written a couple bolts that use `component` to decide on which course of action to take.

After realizing those things, I imagined that something like this might still be useful:

```python
def process_default(self, tup):
    # do something
```
if only so that you could easily implement different processing methods for different streams, which is probably a fairly common use case. 

What I do think would be nicer is if we allowed for retrieving the values from the Tuple by field name, like you can with Java.  This could be accomplished either of two ways:

1.  The Python Topology DSL (#84) being finished.
2.  Submitting another Storm PR to add this information to the handshake that gets sent back from Storm.  It should be as simple as serializing [`TopologyContext.componentToStreamToFields`](https://github.com/apache/storm/blob/master/storm-core/src/jvm/backtype/storm/task/TopologyContext.java#L61) and sending that along.

I actually think the second solution might be better for the community at large, since this would make all Multilang IPC implementations better.

**Comment by kbourgoin** [comment]
I can't say I'm a fan of this.  I think it complicates implementations of bolts for the basic case. `process` --> `process_default` will make no sense for most users since most users don't use streams.  It's not awful, but it requires new users to understand a fairly advanced topic if they want to know why the function is named as such.  The current way to do this would be like this, which I don't find onerous at all:

```python
def process(self, tup):
    if tup.stream == 'foo':
        self._process_foo(tup)
    elif tup.stream == 'bar':
        self._process_bar(tup)
    else:
        self._process_default(tup)
```

and even that can be shortened by putting all the functions in a dict and using that like a switch statement.

```python
def process(self, tup):
    process_fn = self._process_fns.get(tup.stream, self._process_default)
    process_fn(tup)
```

It's a few more lines for the user to write, but `process_default` smells strongly of over-engineering to me.

**Comment by dan-blanchard** [comment]
> It's a few more lines for the user to write, but process_default smells strongly of over-engineering to me.

Fair enough.  Although I do think adding the ability to access tuple values by their names would get rid of most of the original motivation for this issue.

**Comment by kbourgoin** [comment]
Yeah, I wholeheartedly agree with that.  That would be really awesome to have.

**Comment by amontalenti** [comment]
Hmm, I like the "access fields by their name" idea. So, with the new DSL, we could do some sugar like this:

```python
class Bolt(object):
    def get_field(self, tup, field_name):
        try:
            # streams contains a list, like ["word", "count"], when
            # the default stream is used
            i = self.streams.index(field_name)
        except ValueError:
            return None
        v = tup.values[i]
        return v
```

**Comment by dan-blanchard** [comment]
It feels a little weird to me to have `get_field` be a method of the `Bolt` class instead of just having it so we could access the values by name directly, since [that's how it works in Java](https://nathanmarz.github.io/storm/doc/backtype/storm/tuple/Tuple.html) (see all of the `...ByField` methods).  What about if we did something like this where we modified the `Tuple` class we have to have  a `get_field` method and a `_fields` dictionary like this:

```python
class Tuple(namedtuple):
     def get_field(self, field_name):
          return self.values[self._fields[field_name]]
```

and we modified `Component.read_tuple` to be something like this:

```python
class Component(object):
   ...
   def read_tuple(self):
        cmd = self.read_command()
        tup = Tuple(cmd['id'], cmd['comp'], cmd['stream'], cmd['task'],
                    cmd['tuple'])
        # Set the mapping from field names to indices
        tup._fields = self._field_dict[tup.stream]
        return tup
```

Another possibility would be to have `Component` have a dictionary mapping from streams to  `namedtuple` types, so that `tup.values` would just be a `namedtuple` so you could access the values by index or by name like `tup.values.some_field`.  Even though I just wrote up the other solution, I think I actually like this a bit better.

**Comment by msukmanowsky** [comment]
I'm :+1: on adding this to the tuple. But why `get_field()` then and not just override [__getitem__](https://docs.python.org/2/reference/datamodel.html#object.__getitem__)?

```
tup['word']
tup['count']
...
```

**Comment by amontalenti** [comment]
Yea, we could sugar it up that way, indeed.

**Comment by dan-blanchard** [comment]
Yeah, I was saying that we should make `tup.values` the `namedtuple`.  Sorry if that wasn't clear.  I just liked the idea of having values accessible both by index and by name under `tup.values`.  `Tuple` itself already is a `namedtuple`, so overriding `__getitem__` seems a little strange to me there.

What I'm trying to avoid is people going "Oh wait, to get the stream for the tuple, do I use a dot or quotes?"  If all of the values are just stored as a `namedtuple` called `tup.values`, then the separation between Tuple attributes and values is clearer.

**Comment by amontalenti** [comment]
That makes sense to me. `tup.values` as `namedtuple` means that if you need to access one field, you can just do `word = tup.values.word`. If you need to access several fields, you can unpack, like `word, count = tup.values`. This seems to be the best/cleanest option. Shall we split it off as a separate GH issue with relevant information?

**Comment by dan-blanchard** [comment]
Yeah, let's close this one, since I think making `tup.values` a `namedtuple` accomplishes the same thing this proposal was going for in a cleaner way.
