### ISSUE TITLE
zookeeper

### ISSUE THREAD

**Issue by hadisotudeh** [Parsely/streamparse#143]
Hi
I want to know where is the concept of zoo-keeper in streamparse?
When we want to submit our project to cluster, should we install zookeeper manually?
What about storm, nimbus and supervisors?

**Comment by dan-blanchard** [comment]
streamparse has two purposes:

1.  To let you write Storm bolts and spouts in Python so that you don't have to write Java code.
2.  To provide a set of command-line utilities for managing Storm clusters and projects.

To that end, you'll need a properly configured Storm cluster to actually do anything.  You can follow [the instructions provided in the official Apache Storm docs](https://storm.apache.org/documentation/Setting-up-a-Storm-cluster.html) to get setup.
