### ISSUE TITLE
Add support for custom JSON object decoding/encoding

### ISSUE THREAD

**Issue by msukmanowsky** [Parsely/streamparse#149]
Not to be confused with #8, the idea here is that users will have custom objects (good example is `datetime.datetime`) that they'd prefer not to have to serialize before an emit call and automatically deserialized so that logic doesn't complicate their Bolts/Spouts.  Both simplejson and the Python stdlib json packages support this.

Recommend that we allow users to register callback functions for json encoding / decoding and add to the IPC module when reading from stdin / writing to stdout.

Perhaps something like a mixin model, if a `_to_json` or `_from_json` method is defined on the component, it's used:

```python
import base64
import datetime as dt
import random

from streamparse.bolt import Bolt
from streamparse.spout import Spout
import numpy as np
import simplejson as json


class CustomJSONSerializerMixin(object):

    _UNIX_EPOCH = dt.datetime.utcfromtimestamp(0)

    def json_default(self, obj):
        if isinstance(obj, complex):
            return {'__t': 'complex', 'r': obj.real, 'i': obj.imag}
        elif isinstance(obj, dt.datetime):
            # assumes datetime is UTC
            return {'__t': 'datetime', 'v': int((obj - self._UNIX_EPOCH).total_seconds() * 1000)}
        elif isinstance(obj, np.ndarray):
            data_b64 = base64.b64encode(obj.data)
            return {'__t': 'ndarray', 'v': data_b64, 't': str(obj.dtype), 's': obj.shape}

        raise TypeError('%r is not JSON serializable.' % obj)

    def json_object_hook(self, obj):
        obj_type = obj.get('__t')
        if obj_type == 'complex':
            return complex(obj['r'], obj['i'])
        if obj_type == 'datetime':
            return dt.datetime.utcfromtimestamp(obj['v'] / 1000.0)
        if obj_type == 'ndarray':
            data = base64.b64decode(obj['v'])
            dtype = obj['t']
            shape = obj['s']
            return np.frombuffer(data, dtype).reshape(shape)
        return obj


"""Override send_message calls in Bolt and Spout so that it does something
like:

    default_fn = getattr(self, 'json_default', None)
    send_message(msg, default=default_fn)

And similar for read_command:

    object_hook_fn = getattr(self, 'json_object_hook', None)
    read_command(object_hook=object_hook_fn)
"""

class ComplexSpout(Spout, CustomJSONSerializerMixin):

    def next_tuple(self):
        real = random.randint(1, 100)
        imag = random.randint(1, 100)
        self.emit([complex(real, imag)])


class ComplexAdder(Bolt, CustomJSONSerializerMixin):

    def process(self, tup):
        complex_a, complex_b = tup.values
        self.emit([complex_a + complex_b])


if __name__ == '__main__':
    obj = {
        'dt': dt.datetime.utcnow(),
        'complex': complex(10, 5),
        'np': np.arange(100, dtype=np.float)
    }
    serializer = CustomJSONSerializerMixin()
    res = json.dumps(obj, default=serializer._json_default)
    print res
    print json.loads(res, object_hook=serializer._json_object_hook)

```

We'd then tweak the `ipc.send_message` and `ipc.read_command` functions to take the optional callback function.

@dan-blanchard, @kbourgoin or @amontalenti, whatcha think?

**Comment by kbourgoin** [comment]
I'm not sure if you're advocating actually using the object hook facilities in simplejson/json.  If so, the performance consequences of this are monstrous.  Last I looked, it's more than two orders of magnitude slower when you use it.  Don't quote me on that, but I can look it up or run some tests if need be.

I know we *can* add that and say "use at your own risk," but the performance implications are so large that it feels disingenuous to even use it.  It's more like "we implemented it, but never use it if you care about throughput. Ever.".

If you're saying we implement something *like* that facility where we give the raw input and people can handle their own encoding/decoding, that's not a bad idea at all.

**Comment by lthibault** [comment]
@kbourgoin This issue was opened following [a question](https://groups.google.com/forum/#!topic/streamparse/mRuSl3bRE98) I asked on the mailing list.  The point of said question was more about having numpy compatibility than being able to serialize *arbitrary* objects.

Lack of numpy compatibility is a pretty massive hurdle for the vast majority of scientific applications.  Perhaps there's a middle ground whereby we can efficiently pass numpy arrays but not necessarily open the API to such abuse?

This particular issue means a lot to me, so I'd be very happy to contribute a pull-request.  I just need a bit of guidance!

**Comment by kbourgoin** [comment]
Well, it's not just abuse. The problem is that `object_hook` requires going back and forth from the C encode to Python for every object being encoded.  This creates drag to the point where it would be unusable. You'd have a super fast bolt written using numpy, but then it'd spend 40% of its time doing JSON encoding.

That said, I'm not clear on @msukmanowsky's solution. If it's saying to let the user sort it out, I think that's perfect. Then you could figure out how best to encode the numpy array, without the overhead of using that specific json facility.  In fact, if we had an `object_hook`-like facility, we could build it in a generic sense, like this, but then perhaps figure out how to make a high-performance numpy-specific implementation layered on top.

I've got a couple questions about this, but I'll move to the mailing list, which seems more appropriate.

**Comment by lthibault** [comment]
> In fact, if we had an object_hook-like facility, we could build it in a generic sense, like this, but then perhaps figure out how to make a high-performance numpy-specific implementation layered on top.

This sounds very reasonable to me.

See you on the mailing list!  @msukmanowsky Thanks for opening this issue!

**Comment by dan-blanchard** [comment]
This seems similar to the #145 PR, for which I had the same objections as @kbourgoin.

**Comment by dan-blanchard** [comment]
This issue was moved to pystorm/pystorm#6
