### ISSUE TITLE
Virtualenv Python Pycurl Issue

### ISSUE THREAD

**Issue by j105rob** [Parsely/streamparse#157]
When trying to deploy pycurl to a virtualenv via the vitrualenvs/requirement.txt file, pycurl decides to ignore the fact that we are attempting to install it into a virtualenv.

Since it appears that the PYTHONPATH or sys.path is not including the system packages, when the virtualenv is activated, pycurl imports fail.

This is a known issue with the way that pycurl is installed within a virtualenv, outside of the streamparse project. My team has used a workaround (manual) to get this fixed, copying the pycurl.so file into the virtualenv's site-packages.

There should be a way developed for doing pre/post scripting in the virtualenv setup.

**Comment by rduplain** [comment]
This is an issue with the PycURL project (and not streamparse). Searching the web indeed shows many have the same issue with PycURL in a virtualenv, and I see that others have used the same workaround that you have.

Looking at the [PycURL](http://pycurl.sourceforge.net/) homepage:

> [Bugs](https://github.com/pycurl/pycurl/issues) and [patches](https://github.com/pycurl/pycurl/pulls) are tracked on GitHub. If your patch or proposal is non-trivial, please discuss it on the mailing list before submitting code. Older bugs and patches can be found on the [issues](https://github.com/p/pycurl-archived/issues) and [pull requests](https://github.com/p/pycurl-archived/pulls) pages for the temporary Git import repository on Github, and on the [PycURL SourceForge](http://sourceforge.net/projects/pycurl/) project page.

I have searched all three referenced bug trackers of PycURL for virtualenv and have not found anything, which is a bit surprising when Google shows many users working around this issue. I recommend filing a new issue [here](https://github.com/pycurl/pycurl/issues).

**Comment by dan-blanchard** [comment]
> There should be a way developed for doing pre/post scripting in the virtualenv setup.

You should be able to do this by defining a `pre_submit` function in a file in your project's root directory called `fabfile.py`.  When `sparse submit` runs, this will get called automatically after the virtualenv has been setup, and you could use it to fix the missing `.so` file via `fabric`.  

Unfortunately, there is currently a bug in streamparse, which will be fixed in the next release, that makes `pre_submit` not get imported properly unless you also have an empty `tasks.py` file present in your project's root directory (see a10c478ca73b20b16ed97de5f14fe823d1f3b735).
