### ISSUE TITLE
Question: Parallelism and Worker Settings

### ISSUE THREAD

**Issue by jwestboston** [Parsely/streamparse#163]
I've been looking into streamparse and I'm confused (or rather, unaware) of how one sets the number of workers for a topology as well as the parallelism hint for a specific spout or bolt.  I have topologies where I'd like some bolts to run with just a single instance and other bolts to have say 5-10 instances within the storm cluster.

How does one do this with streamparse?

Thanks.

**Comment by amontalenti** [comment]
The :p parameter in the python-bolt-spec for the Clojure DSL will do it.
There are examples in streamparse.rtfd.org. HTH,

-AM (from phone)

**Comment by amontalenti** [comment]
Oh sorry, and for number of workers for a topology, you can specify the -p
option to the "sparse submit" command. That will set the
topology.num.workers flag, iirc.

**Comment by jwestboston** [comment]
@amontalenti Awesome - thanks!

Just to reiterate and make sure I understand .. the `sparse submit -p` flag will set the number of workers for the entire job/topology and the :p in the Closure DSL will set the parallelism hint (aka the number of executors) for the specific spout or bolt.  Correct?

**Comment by amontalenti** [comment]
Bingo. Just note that though you can go crazy with component parallelism
(the rule is, each addition :p number means that many more Python processes
in parallel doing your work), you shouldn't go overboard with worker
parallelism.

The worker parallelism tells Storm to start up more than one JVM process.
In streamparse topologies, however, the workers are already highly
multi-threaded and the main work they do is serialization/deserialization
of the multi-lang protocol JSON, and forwarding data around the cluster.
So, -p1 or -p2 for beefy machines is typically fine. -p16 or -p32 will be
wasteful. Some people prefer to run with -p2 all the time simply so that if
one dies, another one is around until the dead one restarts.

**Comment by rduplain** [comment]
* [ ] Convert this thread to docs.

I'd be happy to.

**Comment by amontalenti** [comment]
@rduplain Do it!
