### ISSUE TITLE
Add `sparse serialize` command.

### ISSUE THREAD

**Issue by rduplain** [Parsely/streamparse#178]
From @amontalenti:

Use `thriftpy` to parse `storm.thrift` and get Thrift data structures that can be used to late out the Topology DAG. Write a (Clojure?) command-line tool `sparse serialize` that simply loads a topology and serializes it in Thrift’s binary format. Then modify the Python Topology DSL (#84) to produce Thrift data structures that can serialize as the same format.

**Comment by rduplain** [comment]
@dan-blanchard says:

> The topology "definition" is just a Thrift file, but you still need to upload all the code to the server in a JAR.

That is, submitting a topology still needs a .jar -- a Thrift definition alone doesn't support submitting the topology (if I'm interpreting Dan correctly).

**Comment by dan-blanchard** [comment]
Correct.  The `storm shell` command referenced [here](https://storm.apache.org/documentation/Defining-a-non-jvm-language-dsl-for-storm.html) does three things to facilitate non-JVM DSLs:

1.  It packages all your code up in a JAR for you.
2.  Uploads the JAR to Nimbus
3.  Calls a script of your choosing with the nimbus host, port, and uploaded JAR location as command-line arguments.

It's the script that's called in the third step that actually needs to connect to Nimbus and submits the topology Thrift definition after the code is already in place on the server.

I feel like their is some context missing from this issue, because it seems unclear why we would want to split the conversion from the Python Topology DSL into the Thrift definition out into a separate tool.

**Comment by rduplain** [comment]
> I feel like their is some context missing from this issue, because it seems unclear why we would want to split the conversion from the Python Topology DSL into the Thrift definition out into a separate tool.

@amontalenti Could you add context?

**Comment by rduplain** [comment]
Do we just want `storm shell`?

**Comment by amontalenti** [comment]
Closing in favor of #213 after discussion with @dan-blanchard.
