### ISSUE TITLE
Add `sparse runserver` command.

### ISSUE THREAD

**Issue by rduplain** [Parsely/streamparse#179]
Add `sparse runserver` which runs a full nimbus/worker/UI locally and makes it possible to submit streamparse topologies to that local/interactive cluster with zero config (quickstart would then use this).

In addition to development use, this could provide useful workflows for digging into exceptions.

**Comment by rduplain** [comment]
This will require having Storm installed, and we should consider that carefully.

**Comment by dan-blanchard** [comment]
I think this could easily just rely on the [Vagrant file we have for the kafka-jvm example](https://github.com/Parsely/streamparse/blob/7d7778ef899c1b44053297f5135af6de74de77f2/examples/kafka-jvm/Vagrantfile).

**Comment by amontalenti** [comment]
@dan-blanchard hmm, -1 on using the vagrant file. Having an `sparse` tool rely on Vagrant feels heavy-handed to me. I think the spirit of this issue is to explore a way to rely upon a local Storm installation being on the `$PATH` (e.g. in an `/opt` directory), but doing the work of spinning up all the necessary subservices locally via Python, e.g. using an approach similar to `docker-compose` where several subprocesses would be spun up (`storm ui`, `storm worker`, `storm nimbus`, `storm logviewer`, `storm devzookeeper`, etc.) and you'd see the output from all in the console directly with some prefix.

**Comment by rduplain** [comment]
+1 to @amontalenti's point. In the birding project, I use a `Procfile` for this. For `sparse runserver`, it could just be a configuration check before forking several processes.

**Comment by amontalenti** [comment]
Closing in favor of #213 after discussion with @dan-blanchard.
