### ISSUE TITLE
Local run of Kafka-JVM

### ISSUE THREAD

**Issue by Nhoutain** [Parsely/streamparse#211]
First of all, thanks for your work.

I try to run kafka-jvm with localhost.
All seems to be fine, I send messages from a NodeJS app which go through kafka topics to arrive at the Spout. 

Zookeeper connection work, kafka connection seems to work because messages arrive but I have two errors (I thinks linked):

1) First I have 
> Read partition information from: /consumers/fifi/partition_0  --> null
> No partition information found, using configuration to determine offset
when storm run with sparse running

2) Secondly, I have a more confusing error which appear only when the spout receive his first messages:
>INFO  org.apache.storm.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x1518e430784000e type:create cxid:0x3 zxid:0x2a txntype:-1 reqpath:n/a Error Path:/rootPath/consumerID Error:KeeperErrorCode = NoNode for /rootPath/consumerID

At the end, I see with zookeepercli that the spout has never create the consumer in /consumers.

Do you have any idea why it's appear? Or at least some way to search... ? I actually search arround google without result.

**Comment by dan-blanchard** [comment]
You say you're using the `kafka-jvm` example.  That's intended to run on a Vagrant VM.  If you're running it on your localhost, you'll need to update `config.json` and make sure you install the same things that are included in [the Vagrantfile](https://github.com/Parsely/streamparse/blob/master/examples/kafka-jvm/Vagrantfile).

Also, since you've written this we've released a develop preview of streamparse 3.0 that switches from using Clojure to Python for specifying the topologies, so the examples are currently only compatible with that release.
