### ISSUE TITLE
How should I run kafka-jvm example?

### ISSUE THREAD

**Issue by CaledoniaProject** [Parsely/streamparse#219]
Hi,

I'm trying out the kafka spout example, but looks like in previous commit, the pixelcount.clj topology file was removed

Now If I do a `sparse run` it would complain about the missing file

So, what's the right way to launch that example?

**Comment by dan-blanchard** [comment]
@CaledoniaProject, since we're planning a major release soon, the examples are not compatible with the current release.  Since you must have cloned the code locally, just checkout the [2.1.x](https://github.com/Parsely/streamparse/tree/2.1.x) branch and you should be able to run things as you would expect.
