### ISSUE TITLE
bug in the wordcount example

### ISSUE THREAD

**Issue by OferE** [Parsely/streamparse#233]
Hi,

I found a bug in the wordcount example.
in wordcount.py
instead of:
self.emit([word, self.counts[word]])

you should have (second argument should be a string):
self.emit([word, str(self.counts[word]))

it turns out that emitting a number will cause the system crash if another bolt is getting this tuple and try to access it...

BTW - you should document somewhere that one should emit only strings...
I just spent 2 hours to understand what is wrong here.
(or maybe it is allowed and the bug is in a different place?)

I am using java7 if this can explain this behaviour

Hope this helps...

**Comment by OferE** [comment]
Thanks for the quick reply. I'll post on Sunday.

On Thu, Mar 31, 2016 at 3:58 PM, Dan Blanchard <notifications@github.com>
wrote:

> There's no reason you should only have to emit strings. Everything gets
> serialized and deserialized as JSON, and that works fine with integers.
> Could you please post whatever traceback you're seeing for the downstream
> bolt?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Parsely/streamparse/issues/233#issuecomment-203923115>
>



-- 
Regards,
Ofer Eliassaf

**Comment by OferE** [comment]
Here is the closure (just adding one more step to the wordcount example):

```Clojure 
(ns wordcount
  (:use     [streamparse.specs])
  (:gen-class))

(defn wordcount [options]
   [
    ;; spout configuration
    {"word-spout" (python-spout-spec
          options
          "spouts.words.WordSpout"
          ["word"]
          )
    }
    ;; bolt configuration
    {"count-bolt" (python-bolt-spec
          options
          {"word-spout" :shuffle}
          "bolts.wordcount.WordCounter"
          ["word" "count"]
          :p 2
          )

    "tryme-bolt" (python-bolt-spec
          options
          {"count-bolt" :shuffle}
          "bolts.tryme.WordPrinter"
          []
          :p 1
          )
    }

  ]
)
```

**Comment by OferE** [comment]
I also tried specifying an integer (i.g. 127) instead of the counter and got the same error.

I have the environment ready if you need anything else.

BTW, It's an amazing project!

**Comment by dacohenii** [comment]
I replicated your setup and I think I have an idea of what's going on here. It looks like the issue is indeed an integer-to-string conversion, but it's happening with this block of code in `WordPrinter`:

```python
        word0 = tup.values[0]
        word1 = tup.values[1]
        self.log('in tryme: ' + word0 + ', ' + word1)
```

In the Clojure file, the input source of `tryme-bolt` is configured to be the output of `count-bolt`, so `tup.values[1]` is an `int` (and thus, so is `word1`). Concatenating `word1` with a string causes Python to raise an exception. However, the message is not logged but instead output to `stderr` (on the VM), so it doesn't get back to the streamparse process.

Updating the `process` function to catch and print the exception will cause the message to log:

```python
    def process(self, tup):

        word0 = tup.values[0]
        word1 = tup.values[1]
        try:
            self.log('in tryme: ' + word0 + ', ' + word1)
        except TypeError as e:
            self.log('\nlooks like a TypeError: %s' % str(e))
```

The fix, in this case, is to cast `word1`, or to just change the log statement to `self.log('in tryme: %s, %d' % (word0, word1))`. 

Casting the value in `WordCounter` fixes your issue because now `WordPrinter` is getting two strings, but the root cause is a Python type casting error, not that you can't emit non-strings.

Hope this helps!

**Comment by dacohenii** [comment]
Actually, looking at it again, I think the exception message may have actually been logged to the console, but I missed it until I knew what I was looking for because it was above the Java exceptions (which makes sense).

**Comment by OferE** [comment]
Thanks!!
בתאריך 7 באפר׳ 2016 5:46,‏ "David Cohen" <notifications@github.com> כתב:
