### ISSUE TITLE
Any good starting points for optimising a streamparse cluster?

### ISSUE THREAD

**Issue by bobbyrenwick** [Parsely/streamparse#248]
I was wondering if you have any good starting points for going about optimising a streamparse cluster?

I've been watching [this talk](https://www.youtube.com/watch?v=cH8hKyf4Y40) and even after having followed most of the starting points there we seem to only be able to pump out 15MB/s (1000 messages/s) from a 3 node cluster with 12 core Xeons, 128GB RAM, 1 Gbit/s NICs. We're using msgpack serialization, Storm v1.0.0 and local or shuffle grouping.

The 15MB/s is with a spout that pulls something off a RabbitMQ queue, 2 bolts that just forward the message they received and then a final bolt that writes back to the same RabbitMQ instance, on a different queue.

If I remove the 2 bolts that do nothing, we can reach 30MB/s (2000 messages/s) so it seems there's a huge overhead in the serialization and moving around of tuples between workers.

As soon as we replace the 2 bolts that do nothing with some bolts that actually do CPU intensive work (both ~100ms of computation) our throughput drops down to about 1.5MB/s.

What sort of throughput do you guys see with Streamparse? Does it also render the "Capacity" metric in Storm UI useless because our Execute latency is just writing to stdout? Do you guys use another metric instead, based on process latency perhaps?

**Comment by dan-blanchard** [comment]
It sounds like your components simply aren't doing enough work compared to the serialization overhead.  You can fix that in a couple ways:

1.  Have you spout batch your tuples into larger tuples. For example, we currently use a spout in production that pulls things out of Kafka and chunks them of 100. This reduces our serialization overhead by a lot, and the downstream components just need to be adjusted so that they expect tuples containing lists, and iterate through the lists.
2.  Collapse components you currently have separated into single components.  The more components you have, the more you're stuck dealing with serialization overhead.  You especially want to move any filtering (if you do that) into the spout itself if you're trying to achieve maximum throughput, since then you never have to deal with the serialization overhead at all.
