### ISSUE TITLE
3.0.0.dev3: error: No topology definitions are defined in topologies/

### ISSUE THREAD

**Issue by alecswan** [Parsely/streamparse#249]
After updating from 2.4 to 3.0.0.dev3 I am getting the following error:
```
> sparse run
error: No topology definitions are defined in topologies/.
```
I checked out 3.0.0.dev3 code and it looks like in https://github.com/Parsely/streamparse/commit/146736b83258bed841ec9ad52f3136e09f71cf11 a switch from Closure to Python topology definitions was made. Is the new topology schema documented anywhere? What's the migration path? Should I be able to use streamparse 2.4 to deploy topologies to Storm 1.0 (I am having problems with that, hence tried 3.0.0.dev3)?

Thanks!

**Comment by dan-blanchard** [comment]
Sorry if the release notes don't make it obvious enough, but you can read all about the new topology DSL in [our `master` docs](http://streamparse.readthedocs.io/en/master/topologies.html).

**Comment by dan-blanchard** [comment]
> What's the migration path?

Oh, and the migration path is that you convert your topologies from Clojure to Python. We don't provide an automated tool to do this because it's the Python DSL is so much easier to read/write that manually doing it shouldn't be too much of a burden.


> Should I be able to use streamparse 2.4 to deploy topologies to Storm 1.0 (I am having problems with that, hence tried 3.0.0.dev3)?

I haven't tried, but it probably would not work because they changed all the Java full class names from starting with `backtype` to `org.apache`, so our old Clojure interop library probably does not work with it.

**Comment by pbhosale87** [comment]
@alecswan : Hi, How did you achieve this? i am facing similar issue. We have all the topologies in closure.
