### ISSUE TITLE
What is the best way to manage the inputs from more than one bolt?

### ISSUE THREAD

**Issue by fedelemantuano** [Parsely/streamparse#317]
Is there a standard method to manage the inputs from more than one bolt?

I have three bolts (A, B, C) that do something. Then there is bolt MERGE that should merge A, B and C emits and output merge result.

[I'm using a RAM storage in MERGE bolt](https://github.com/SpamScope/spamscope/blob/v1.0/src/bolts/json_maker.py#L111-L125), and I waiting tuple from A, B, C. But is this the best way?

**Comment by dan-blanchard** [comment]
In the past I've done pretty much what you have when dealing with this issue:

1.  Use a `fields` grouping on the ID that we will use for joining.
2.  Store the values we've received for a given ID until we have all of the ones we were expecting.
3.  Process the values we stored when we have them all for a given ID.

One tip I can offer is that rather than hard-coding the list of inputs your bolt is expecting, you can actually just set that list to `list(self.context['source->stream->grouping'].keys())` if you're using a version of Storm newer than 0.10.0.  That will contain a list of all of the bolts that feed into the current one.  You can see more details about what kind of info you can pull out of `Bolt.context` [here](http://storm.apache.org/releases/1.0.2/Multilang-protocol.html).
