### ISSUE TITLE
Merge pystorm back into streamparse and rebrand?

### ISSUE THREAD

**Issue by dan-blanchard** [Parsely/streamparse#329]
At this point, pyleus is no longer in development, so the whole point of having a separate pystorm project is moot. To simplify releases, maybe we should just move pystorm back into streamparse and rebrand streamparse as pystorm, since it's got the better name and logo.

**Comment by dan-blanchard** [comment]
@msukmanowsky @kbourgoin @amontalenti Thoughts?

**Comment by msukmanowsky** [comment]
I'm +1 on merging but probably 0 on any rebranding. The logo I don't care about. I get that pystorm has a literal appeal to it, but streamparse is a known entity within the community.

I think the better idea here is to update official Storm docs to list supported multilang clients like streamparse so that new users are aware of things. I was amazed to find today that storm.apache.org has no mention of any multilang implementations (minus the link to @amontalenti 's PyData talk here http://storm.apache.org/talksAndVideos.html) leaving people to fend for themselves.

**Comment by amontalenti** [comment]
Let's hold off on this ticket a bit. Storm community has some interest in us contributing pystorm to the core. If that were true, maintaining streamparse as a project outside Storm core might be useful.

**Comment by dan-blanchard** [comment]
Ah, good point @amontalenti. That would probably make the most sense.

**Comment by dan-blanchard** [comment]
Closing for now.
