### ISSUE TITLE
feature request: cli commands options documentation

### ISSUE THREAD

**Issue by mbande** [Parsely/streamparse#334]
e.g. ```sparse help stats``` to show ```stats``` options

**Comment by Darkless012** [comment]
you mean 
`sparse stats -h`

**Comment by mbande** [comment]
i don't know this command exists
this is the one that should be documented!

**Comment by dan-blanchard** [comment]
I was initially about to comment that most commands traditionally take a `-h` or `--help` option and that this should be obvious, but I realized if you run `sparse -h` it is not obvious that `--help` works for all the sub-commands if you put it after the command.  For example, `sparse stats -h` will show help for the `stats` sub-command, but `sparse -h stats` will show help for `sparse` itself. We should probably just make a `help` sub-command that is an alias to `sparse SUBCOMMAND -h`, and when we document it we can make it clear that since it's an alias, you can also do `sparse SUBCOMMAND -h`.
