### ISSUE TITLE
Can't name topology `email.py` or `test.py`

### ISSUE THREAD

**Issue by andrewkcarter** [Parsely/streamparse#350]
streamparse (3.1.1)
I ran into a curious thing when one out of several of our topologies would fail to submit.
```
$ sparse submit -n email
Traceback (most recent call last):
  File "/virtualenvs/streamparse3/bin/sparse", line 11, in <module>
    sys.exit(main())
  File "/virtualenvs/streamparse3/lib/python2.7/site-packages/streamparse/cli/sparse.py", line 56, in main
    args.func(args)
  File "/virtualenvs/streamparse3/lib/python2.7/site-packages/streamparse/cli/submit.py", line 244, in main
    override_name=args.override_name)
  File "/virtualenvs/streamparse3/lib/python2.7/site-packages/streamparse/cli/submit.py", line 150, in submit_topology
    topology_class = get_topology_from_file(topology_file)
  File "/virtualenvs/streamparse3/lib/python2.7/site-packages/streamparse/util.py", line 439, in get_topology_from_file
    raise ValueError('Could not find topology subclass in topology module.')
ValueError: Could not find topology subclass in topology module.
```
I finally tracked it down to the name of the topology file. If I renamed it from `email.py` to something else, it worked just fine. In the process of troubleshooting it further, I discovered that `test.py` will also fail.

Here is a minimal topology I verified this with:
```
from streamparse import Topology, Spout, Stream


class TestSpout(Spout):
    outputs = [Stream(fields=['default'], name='default')]

    def next_tuple(self):
        return None


class TestTopology(Topology):

    spout = TestSpout.spec(
            name='Spout',
            par=1
    )
```
Place this in a filed named `email.py` or `test.py` to see it fail, and apparently any other filename to see it succeed.

**Comment by dan-blanchard** [comment]
This is because `sys.path` has modules named `email` and `test` earlier in it than the directory your topologies are in. We could use `sys.path.insert(0, ...)` instead of `sys.path.append(...)` to make your stuff get imported first, but that could lead to weird side effects if another package down the line tried to use the `email` package in the standard library.

There are workarounds for importing modules based on absolute paths, but they're horrible to get to work across Python versions because they keep changing `importlib`.

**Comment by codywilbourn** [comment]
@andrewkcarter It seems like your question has been answered by Dan so I'm closing this ticket. Please re-open it if that answer wasn't sufficient.
