### ISSUE TITLE
setNumTasks() function in streamparse?

### ISSUE THREAD

**Issue by LImoritakeU** [Parsely/streamparse#370]
Hello!
It's feeling so good using streamparse and python to build storm topology.

However, is there any way to set particular task for components? 
With Java API, we can use setNumTasks() to do that.

And I am also confused the `direct_task` variable usage in emit() function.
In pystorm.component source code's commit :
```
        :param direct_task: the task to send the Tuple to.
        :type direct_task: int
```
But in streamparse API
```
direct_task (int) – the task to send the Tuple to if performing a direct emit.
```
Is that means this parameter is useless if not DIRECT grouping ?

Thanks!

**Comment by dan-blanchard** [comment]
The `par` argument to the `spec` method we use as part of the topology DSL (as shown in [this example](https://github.com/Parsely/streamparse/blob/master/examples/redis/topologies/wordcount_mem.py#L14)) does basically the same thing as `setNumTasks()` in Java. You can see more details [here](https://streamparse.readthedocs.io/en/stable/topologies.html#parallelism-and-workers).

Yes, you are correct that `direct_task` does nothing unless you're using a `DIRECT` grouping.

**Comment by LImoritakeU** [comment]
Thanks for answer ~

**Comment by LImoritakeU** [comment]
Thanks for answer!

Today I found another way changing task with same executor using **topology.tasks**

example:
```python
    splitter = SplitterBolt.spec(
        inputs={consumer: Grouping.SHUFFLE},
        par=6,
        config={'topology.tasks': 20})
```
![](http://i.imgur.com/IkunEEu.png)

**Comment by dan-blanchard** [comment]
@LImoritakeU it is a good point that you can increase the number of tasks that way, but I have never seen a case where increasing the number of tasks (instead of executors) actually helps for a Python/Multilang-based Storm topology. Increasing the number of executors will increase the number of Python processes running, which is usually all you want/need. It is unclear what increasing the number of tasks would actually do for a Python-based topology, where each Python process is limited by the GIL and is associated with a single JVM executor thread.
