### ISSUE TITLE
Virtualenv name in config.json when `install_virtualenv` is set to false

### ISSUE THREAD

**Issue by tanaysoni** [Parsely/streamparse#371]
Hello!

I want to deploy topologies in a prod cluster where Storm nodes don't have SSH access, hence using fabric to install virtualenv is not possible. 

From what I understand, if `install_virtualenv` is set to false, there are two options

- by default, streamparse excepts a virtualenv named as the topology
- or, set `use_virtualenv` to false

Is there a way to configure topology to use a specific virtualenv? Since the topologies to be deployed have the same dependencies, I plan to pre-install a virtualenv on Supervisor nodes which all topologies could use.

One possible solution is adding `virtualenv_name` in config.json, which overrides the default virtualenv that streamparse looks for.

**Comment by dan-blanchard** [comment]
@tanaysoni I'd welcome a pull request to add `virtualenv_name`, but plumbing that through might be a bit more complex than you'd initially think because we explicitly use `topology_name` for that in a few different places.

That said, for now a simple workaround would be to just set `install_virtualenv` to `False`, and then just create symlinks inside `virtualenv_root` that point to the virtualenv you'd like to share.
