### ISSUE TITLE
Support multiple versions of python

### ISSUE THREAD

**Issue by anuraguniyal** [Parsely/streamparse#399]
How can I use a multiple topologies some of which use python2 and some python3. Easiest way I can think is that "virtualenv" command should be configurable so user can point it to correct path.

Also python3 doesn't have virtualenv command, so it would also help there if I can just say
"virtualenv": "python3 -m venv" in config

**Comment by anuraguniyal** [comment]
Any updates on this, ability to set virtualenv command would be great.

**Comment by dan-blanchard** [comment]
Currently there is no support for doing this. I would welcome a PR to add virtualenv command customization but that would be per config file and not per topology. 

Figuring this out on a per topology basis is high on my list of priorities right now because I also need this functionality. I would also love to extend it to address #183 as well, but we'll see if I can do that on the first pass.

All that said, you can currently specify the path to the Python interpreter you want to use in your config file as [shown here with the `-p` virtualenv flag](http://streamparse.readthedocs.io/en/latest/quickstart.html?highlight=virtualenv_flags#disabling-configuring-virtualenv-creation). It works fine with Python 3 even without changing the command to use `venv`.

**Comment by codywilbourn** [comment]
@anuraguniyal We merged a change into master that will be in the next release. You can override the `virtualenv_flags` to specify the version of python used during virtualenv creation. If the virtualenv name already exists on the machines you should delete it prior to deploying with this new setting.

```
class WordCount(Topology):
    # WordCount only will use python3, everything else will use virtualenv_flags in config.json
    config = {"virtualenv_flags": "/path/to/python3"}

```

**Comment by anuraguniyal** [comment]
cool thanks.

**Comment by codywilbourn** [comment]
In the https://github.com/Parsely/streamparse/releases/tag/v3.11.0 release
