### ISSUE TITLE
sparse submit and sparse list should not require SSH tunnels

### ISSUE THREAD

**Issue by amontalenti** [Parsely/streamparse#96]
Currently, when you run `sparse submit` or `sparse list`, the streamparse code opens an SSH reverse tunnel to your configured cluster in config.json and then connects to the SSH-forwarded port.

However, there are use cases where Storm is running *directly* on your machine, or running in a Virtualbox VM or Docker container which is port-forwarded at the network level to localhost. In these cases, especially in the Docker case, SSH is not a viable option for communicating with the nimbus. It should, instead, connect directly to the nimbus at the exposed port.

In the case of `sparse submit`, this also means that virtualenv setup steps cannot run.

I am also going to link this issue to every issue that is dealing with SSH problems.

**Comment by amontalenti** [comment]
SSH related issues: #54, #45

**Comment by dan-blanchard** [comment]
This would be fantastic. The lack of a simple Docker setup has been a sticking point for a few people at ETS.

**Comment by dan-blanchard** [comment]
Also, does this mean you would move away from fabric? That would solve some lingering Python 3 compatibility issues because of fabric not being officially compatible.

**Comment by amontalenti** [comment]
@dan-blanchard I don't think issue means moving away from Fabric just yet. It's just not using SSH for these commands in the case where you happen to be running it locally. Do you think moving away from Fabric is a good idea? I was thinking of moving away from Invoke and only using Fabric, as discussed in #45.

**Comment by dan-blanchard** [comment]
@amontalenti Fabric isn't scheduled to have official Python 3 support until 2.0, which has been pushed back many times at this point.  Unfortunately, the fork we're using doesn't actually work for `sparse submit` at all.  It doesn't report any exceptions either, which makes that failure silent and confusing.

Anyway, are there other cases where you would still want to use SSH connections?  I guess you still need SSH to setup the virtual environments, but I wish there was some way around it (like putting all of that directly in the JAR that gets built).

**Comment by codywilbourn** [comment]
I noticed in testing pull request #69 that the log path defaulted to empty and topology_name defaulted to None when trying to run sparse list locally. This should be looked into when this bug is addressed because it may not be just SSH connections

**Comment by hadisotudeh** [comment]
Are the following errors because of that, too? What should I do?

ssh tunnel to Nimbus 172.20.21.2:6627 established.
Routing Python logging to /home/hadi/Desktop/Storm/log.
Running lein command to submit topology to nimbus:
lein run -m streamparse.commands.submit_topology/-main topologies/topology.clj --option 'topology.workers=2' --option 'topology.acker.executors=2' --option 'topology.python.path="/home/hadi/Desktop/Storm/topology/bin/python2.7"' --option 'streamparse.log.path="/home/hadi/Desktop/Storm/log"' --option 'streamparse.log.max_bytes=100000' --option 'streamparse.log.backup_count=10' --option 'streamparse.log.level="info"'
{:option {streamparse.log.level info, streamparse.log.backup_count 10, streamparse.log.max_bytes 100000, streamparse.log.path /home/hadi/Desktop/Storm/log, topology.python.path /home/hadi/Desktop/Storm/topology/bin/python2.7, topology.acker.executors 2, topology.workers 2}, :debug false, :port 6627, :host localhost, :help false}

channel 1: open failed: connect failed: Connection refused
channel 2: open failed: connect failed: Connection refused

Caught exception: org.apache.thrift7.transport.TTransportException

nimbus is "172.20.21.2"
worker is "172.20.21.95" and worker is my own machine but nimbus is another machine.

**Comment by codywilbourn** [comment]
Hi @hadisotudeh, are you trying the pull request locally? I wrote the PR expecting Storm and Nimbus to be both on the localhost. One possible workaround until I address this is to setup the SSH tunnel manually to Nimbus and tell streamparse not to automatically setup tunnels.

**Comment by codywilbourn** [comment]
@hadisotudeh I was thinking about your issue and I don't think it's related to the SSH tunneling to Nimbus.

The only thing streamparse tunnels to is Nimbus. Since your Nimbus is on another host, this works fine without #98.

I believe it may be related to this server fault question
http://serverfault.com/questions/489192/ssh-tunnel-refusing-connections-with-channel-2-open-failed

The ssh tunnel context manager has this:
```
ssh_cmd = ["ssh",
               "{user}@{host}".format(user=user, host=host),
               "-NL",
               "{local}:localhost:{remote}".format(local=local_port,
                                                   remote=remote_port)]
```
In that question, the remote host didn't like "localhost" in the remote tunnel. For purposes of testing, I'd verify this by setting up a tunnel using this format, and also changing `localhost` to `127.0.0.1` or updating the `/etc/hosts` file on the Nimbus server.

Afterwards, since the worker is on localhost you will need the ability to SSH into localhost without a password. It doesn't require this pull request since streamparse doesn't tunnel into the workers.

**Comment by hadisotudeh** [comment]
@codywilbourn
I checked what you've said. I set 127.0.0.1 as worker and I can ssh to
hadi@127.0.0.1 without password
there is no problem here. but about the first part, should I set up a
tunnel manually?
my nimbus is in another laptop but my worker is my own machine.

**Comment by dan-blanchard** [comment]
Fixed in #112

**Comment by gselvarajan** [comment]
@hadisotudeh , I saw few posts from you and I'm also getting the same error message. How did you resolve this issue ? The error happens when I do submit or list.

985  [main] INFO  backtype.storm.thrift - Connecting to Nimbus at localhost:6627
channel 1016: open failed: administratively prohibited: open failed
Exception in thread "main" org.apache.thrift7.transport.TTransportException

I verified sshd_config/firewall/security and all are seems ok.

**Comment by hadisotudeh** [comment]
I could not resolve the issue, so I switched to Pyleus
<http://yelp.github.io/pyleus/>.

**Comment by dan-blanchard** [comment]
@gselvarajan are you using the latest version of streamparse?  Previous versions did not actually use your `.ssh/config`, which would be the likely cause of such an issue.

Can you SSH into the VM outside of streamparse?

You may want to check out [this Unix Stack Exchange question](http://unix.stackexchange.com/questions/14160/ssh-tunneling-error-channel-1-open-failed-administratively-prohibited-open) about it.  It has some good troubleshooting tips.

**Comment by gselvarajan** [comment]
Thanks @hadisotudeh. 
@dan-blanchard  I'm using stream parse 1.0.1.

**Comment by dan-blanchard** [comment]
@gselvarajan The latest release is 2.0.2.  Give that a try and let me know if you still experience the same problem.

**Comment by Nhoutain** [comment]
@dan-blanchard  I actually have the same issues when I try to ´´´sparse submit´´´ with sparse 2.1.3 after setting ~/.ssh/config and /etc/host. 
The connection work outside streamsparse.
